-- Victor's Events Supabase schema
-- Run this in Supabase SQL editor.

create extension if not exists "pgcrypto";

create table if not exists services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  price numeric(12,2) not null check (price > 0),
  image_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists portfolio (
  id bigint generated by default as identity primary key,
  image_url text not null,
  description text not null,
  created_at timestamptz not null default now()
);

create table if not exists admin_users (
  id uuid primary key,
  email text unique not null,
  hashed_password text,
  created_at timestamptz not null default now()
);

create table if not exists bookings (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  service_id bigint not null references services(id) on delete restrict,
  date date not null,
  message text not null,
  payment_status text not null default 'pending' check (payment_status in ('pending', 'paid', 'failed')),
  created_at timestamptz not null default now()
);

create index if not exists idx_bookings_date on bookings(date);
create index if not exists idx_bookings_service_id on bookings(service_id);

-- RLS
alter table services enable row level security;
alter table portfolio enable row level security;
alter table admin_users enable row level security;
alter table bookings enable row level security;

-- Public read access for public content
create policy "public read services" on services
for select to anon, authenticated using (true);

create policy "public read portfolio" on portfolio
for select to anon, authenticated using (true);

-- Authenticated admins can manage data. API service role bypasses RLS by default,
-- but these policies support direct Supabase access where needed.
create policy "admin manage services" on services
for all to authenticated using (exists (select 1 from admin_users a where a.id = auth.uid()));

create policy "admin manage portfolio" on portfolio
for all to authenticated using (exists (select 1 from admin_users a where a.id = auth.uid()));

create policy "admin manage bookings" on bookings
for all to authenticated using (exists (select 1 from admin_users a where a.id = auth.uid()));

create policy "admin read users" on admin_users
for select to authenticated using (id = auth.uid());

-- Public insert for booking form
create policy "public create booking" on bookings
for insert to anon, authenticated with check (true);

-- Seed services
insert into services (title, description, price, image_url)
values
  ('Tents & Chairs', 'Elegant and durable tent setups for indoor/outdoor celebrations.', 35000, 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1200&q=80'),
  ('Catering', 'Buffet and plated menus with professional service crew.', 50000, 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=1200&q=80'),
  ('Wedding Gowns', 'Bridal gown fitting, styling and accessories coordination.', 20000, 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80'),
  ('Decor', 'Floral and themed decor concepts tailored to your event.', 40000, 'https://images.unsplash.com/photo-1529634895111-9aa2c4d8f8fe?auto=format&fit=crop&w=1200&q=80'),
  ('PA Systems', 'High quality PA systems with event technician support.', 18000, 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80'),
  ('Honeymoon Booking', 'End-to-end honeymoon destination and travel planning.', 25000, 'https://images.unsplash.com/photo-1499678329028-101435549a4e?auto=format&fit=crop&w=1200&q=80')
on conflict do nothing;

-- Seed 12+ portfolio items
insert into portfolio (image_url, description)
values
  ('https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80', 'Elegant wedding reception setup with custom decor.'),
  ('https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80', 'Styled dining tables for a premium celebration experience.'),
  ('https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1200&q=80', 'Outdoor marquee and tent layout for large guest events.'),
  ('https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80', 'Bridal bouquet and ceremony styling details.'),
  ('https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80', 'Cake presentation and floral arrangement for weddings.'),
  ('https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80', 'Corporate and social event seating with branded finishing.'),
  ('https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=80', 'Garden wedding aisle with romantic drape concepts.'),
  ('https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=1200&q=80', 'Buffet and live catering station service in action.'),
  ('https://images.unsplash.com/photo-1478146896981-b80fe463b330?auto=format&fit=crop&w=1200&q=80', 'Night reception lighting and dance floor ambience.'),
  ('https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80', 'Cocktail lounge area designed for guest comfort.'),
  ('https://images.unsplash.com/photo-1505236858219-8359eb29e329?auto=format&fit=crop&w=1200&q=80', 'Ceremony entrance styling and photo-friendly backdrop.'),
  ('https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=80', 'Full event execution from decor to guest dining flow.')
on conflict do nothing;

-- Admin setup guidance:
-- 1) Create admin user in Supabase Auth (Authentication > Users > Add User)
-- 2) Insert user into admin_users with Auth UID:
--    insert into admin_users(id, email)
--    select id, email from auth.users where email = 'admin@victorsevents.co.ke';
-- 3) Login from frontend admin page with same credentials.
